import './globals.css'
import type { Metadata } from 'next'

import UILayout from './UILayout'
import RainbowKitWrapper from './RainbowKitWrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <RainbowKitWrapper>
          <UILayout>{children}</UILayout>
        </RainbowKitWrapper>
      </body>
    </html>
  )
}
