import "./globals.css";
import type { Metadata } from "next";

import UILayout from "./UILayout";
import WagmiConfigWrapper from "./WagmiConfig";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WagmiConfigWrapper>
          <UILayout>{children}</UILayout>
        </WagmiConfigWrapper>
      </body>
    </html>
  );
}
