import './globals.css'
import type { Metadata } from 'next'

import UILayout from './UILayout'
import RainbowKitWrapper from './RainbowKitWrapper'

import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <RainbowKitWrapper>
          <ToastContainer
            position="bottom-right"
            theme="dark"
            closeButton={false}
          />
          <UILayout>{children}</UILayout>
        </RainbowKitWrapper>
      </body>
    </html>
  )
}
